export enum PlayerState {
  IDLE = 'IDLE',
  LOADING = 'LOADING',
  READY = 'READY',
  PLAYING = 'PLAYING',
  PAUSED = 'PAUSED',
  SEEKING = 'SEEKING',
  BUFFERING = 'BUFFERING',
  ENDED = 'ENDED',
}
